mutation CreateConnection(
    $service: ENUM_CONNECTIONS_SERVICE!,
    $workspaceId: ID!,
    $data: JSON!) {
  createConnection(
    input: {
      data: {
        service: $service,
        workspace: $workspaceId,
        data: $data
      }
    }
  ) {
    connection {
      id
      service
      created_at
      workspace {
        id
      }
      data
    }
  }
}
