mutation CreateDeliverable(
    $title: String!,
    $slug: String!,
    $workspaceId: ID!,
    $workflowData: [ComponentWorkflowsWorkflowStepInstanceInput!],
    $workflowId: ID!) {
  createDeliverable(
    input: {
      data: {
        title: $title,
        slug: $slug,
        workspace: $workspaceId,
        data: {
          html: "",
          brief: "",
        },
        workflow_data: $workflowData,
        workflow: $workflowId,
      }
    }
  ) {
    # TODO: Factor out GetDeliverableBySlug into a fragment and make it cacheable.
    deliverable {
      id
      created_at
      slug
    }
  }
}
