query DeliverablesByWorkspace($workspaceSlug: String!) {
  deliverables(where: { workspace: { slug: $workspaceSlug } }) {
    id
    title
    slug
    data
    updated_at
    workflow {
      name
      steps {
        id
        label
        slug
      }
    }
    workflow_data {
      deadline
      assignee {
        id
        display_name
      }
      completed
      rejected
      step {
        id
      }
    }
  }
}
