
query DeliverableBySlug($deliverableSlug: String!) {
  deliverables(where: { slug: $deliverableSlug }) {
    id
    updated_at
    title
    data
    attachments {
      name
    }
    workspace {
      name
      slug
    }
    workflow {
      name
      steps {
        id
        label
        slug
        view {
          layout {
            rows {
              value
              unit
            }
            columns {
              value
              unit
            }
            components {
              column_start
              row_start
              column_span
              row_span
              component {
                name
              }
            }
            gap {
              value
              unit
            }
          }
        }
      }
    }
    workflow_data {
      deadline
      assignee {
        username
      }
      completed
      step {
        id
      }
    }
  }
}
