query GetWorkspaceBySlug($workspaceSlug: String!) {
  workspaces(where: { slug: $workspaceSlug }) {
    id
    name
    slug
    updated_at
    pages {
      id
      trend
      url
      slug
      presentation
      title
      viewCountDelta
      trackingType
    }
  }
}
