query ListWorkflowsByWorkspace($workspaceSlug: String!) {
  workflows(where: { workspace: { slug: $workspaceSlug } }) {
    id
    name
    steps {
      id
      label
      slug
      custom_role {
        id
        name
        users {
          id
          display_name
        }
      }
    }
  }
}
