mutation UpdateDeliverable(
  $id: ID!
  $data: JSON
  $title: String
  $slug: String
  $workflowData: [editComponentWorkflowsWorkflowStepInstanceInput]
) {
  updateDeliverable(
    input: {
      where: { id: $id }
      data: {
        title: $title
        data: $data
        slug: $slug
        workflow_data: $workflowData
      }
    }
  ) {
    deliverable {
      id
      updated_at
    }
  }
}
