name: Cypress

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-e2e-tests:
    runs-on: ubuntu-20.04
    name: End-to-end tests / Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome
          config-file: cypress-e2e.json
        env:
          API_URL: https://dev.api.editori.io
          BACKEND_URL: https://dev.api.editori.io/graphql
          CLIENT_BASE_URL: http://localhost:3000
          NODE_ENV: staging
          NPM_CONFIG_PRODUCTION: false

  cypress-component-tests:
    runs-on: ubuntu-20.04
    name: Component tests / Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          command: yarn cypress run-ct
          wait-on: 'http://localhost:3000'
          browser: chrome
          config-file: cypress-components.json
        env:
          API_URL: https://dev.api.editori.io
          BACKEND_URL: https://dev.api.editori.io/graphql
          CLIENT_BASE_URL: http://localhost:3000
          NODE_ENV: staging
          NPM_CONFIG_PRODUCTION: false
